### ISSUE TITLE
DPP trace algorithm test in CI

### ISSUE THREAD

**Issue by jaromil** [interfacerproject/zenflows#46]
When DPP trace is aligned between lab/notebook tests and production backend, lock down results expected on deterministic input by including it into a CI test using python.

**Comment by sbocconi** [comment]
Test now runs in my repo, but it should run in https://github.com/interfacerproject/zenflows which, as far as I can see, has no tests?

**Comment by sbocconi** [comment]
Tested locally, waiting for resolution of #53 to make a pull request

**Comment by srfsh** [comment]
@sbocconi Sorry for the context switching, but I believe everything regarding this is fine now.  Can I merge your branch into master now and close this down?

**Comment by srfsh** [comment]
> I believe you can, but you (or me) need to change the triggering event and the repo's branch clone to master, right?

I can handle it.  Molto grazie!
